### ISSUE TITLE
Kind icons are not displayed in AC panel with font_size < 11

### ISSUE THREAD

**Issue by deathaxe** [jwortmann/brackets-theme#2]
With `font_size: < 11`

![grafik](https://user-images.githubusercontent.com/16542113/126862736-fb860e03-60ae-4ce6-9990-b9c316e43c7b.png)

With `font_size: >= 11`

![grafik](https://user-images.githubusercontent.com/16542113/126862759-43c94164-30c0-48c5-af33-3e0d2d348355.png)

- ST 4112
- Windows 10 21H1
- 4K 150%
- opengl (doesn't matter)

**Comment by jwortmann** [comment]
Thanks for the reports.

I have set a fixed value for the kind letters (they are just drawn with transparent color and the icon is the background texture) in 4d906c89b29ad291063a17824aa02e44d8ce0cde. I assume it could still be an issue if the system font is set to a different font face (from Segoe UI?) with smaller letter shapes (not sure what font macOS and Linux uses by default). But I can't really set the font.face to a certain font, because it might not be present on other operating systems. Now that I think of it, I should probably gate the fixed font size behind a "platforms" key.

There is also still a bit room in the PNG icons to remove a bit of the transparent margin. Maybe that would be a better approach.

**Comment by deathaxe** [comment]
It may also be related with margins. Those are responsible to define canvas size for drawing icons. If it is not large enough textures disappear. I had a similar issue with the "search" icon in command palette earlier - don't recall the details so.

Tried to add one of your icons to DAneo completions by just setting the `layer0.texture` and it was displayed for all font sizes.

ST uses Consolas by default, on Windows, doesn't it? Also tried with Iosevka and JetBrains Mono. Behavior was always the same.

I'd which we could just customize font.face and signs ST adds, so we could directly use the Codefont.

**Comment by jwortmann** [comment]
> It may also be related with margins. Those are responsible to define canvas size for drawing icons.

Yes, but for the kind_container, these content_margins control the space around the (invisible) kind letter.
https://github.com/jwortmann/brackets-theme/blob/4d906c89b29ad291063a17824aa02e44d8ce0cde/Brackets.sublime-theme#L1180-L1186

I was under the assumption that the kind letters use the (proportional) system font, which can be overriden in the theme via the `font_face` variable, but actually it doesn't seem to have an influence for the kind letters. However, the editor font face which is set in the global preferences is apparently also not used for the font letters by default.

I will have to experiment with it a bit, later.

**Comment by jwortmann** [comment]
DAneo uses Consolas for the kind icons, because "kind_icon_font" is set to "monospace". If no font is set at all, ST seems to use the "system" font by default, which is Segoe UI in Windows. I guess the kind font size in DAneo is a fixed value too, and the kind_container is always big enough, so that the icon texture worked even with small font sizes.

I have tweaked the margins for the Segoe UI, San Fransisco and Ubuntu fonts, so that the kind_container should always have a 25x25 pixel size (with 100% UI scaling). In addition, I've reduced the PNG image size of the icons by 3 pixels. This should be enough, so that the kind_container is still big enough for the texture to fit, even if the "system" font is set to a different font (on Windows this is possible via a few registry keys for example). And I've also added a variable for this font, for easy customization.

So I think this issue is fixed now, for all user font sizes and kind icon fonts.
