### ISSUE TITLE
Latsest release breaks various icon assignments of A File Icon

### ISSUE THREAD

**Issue by deathaxe** [jwortmann/brackets-theme#3]
Effected icons:

- at least JavaScript, Handlebars/Mustache

Packages shouldn't event new `file_type_...` names if some exist already in other packages (also other themes) as this is very likely to cause no icons to be displayed at all for conflicting types.

**Comment by jwortmann** [comment]
This theme doesn't claim to have support / compatibility with the A File Icon package. Existing icon packages and themes already use conflicting names for the icons, for example file_type_cpp in [FileIcons](https://github.com/braver/FileIcons) vs. file_type_c++ in A File Icon. So there is simply no way to solve this and guarantee compatibility with all other packages and themes. The only reliable solution is to follow the advice from https://forum.sublimetext.com/t/sublime-text-3-file-icons-in-sidebar/21134/27, see also the [corresponding section](https://github.com/jwortmann/brackets-theme#file-icons) in my Readme. The icon names used here follow a consistent naming scheme (JavaScript) and/or reuse names from other themes, like [file_type_handlebars](https://github.com/SublimeText/Spacegray/blob/8d4a59de254a27cc7c588c07a6a86662c0cf48d8/prefs/file_type_handlebars.tmPreferences). By the way, the icons for both JavaScript and Handlebars work fine when I install A File Icon additionally to this theme. It are just some other icons for file types which are not supported by A File Icon at all, that either have no color or show the default icon.

Anyways, since you are apparently blocking my perfectly valid and already approved PR for no rational reason, you should not expect any future cooperation from my side regarding your requests.
